include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/core/localization/**]

  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
